"""add feedback_type to public reports

Revision ID: f8a562adfad3
Revises: 28a3ec037f64
Create Date: 2026-03-23 21:31:40.188062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a562adfad3'
down_revision = '28a3ec037f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_reports', schema=None) as batch_op:
        batch_op.drop_column('feedback_type')

    # ### end Alembic commands ###
